// <auto-generated />
using System;
using Gestion_Projet.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Projet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Gestion_Projet.Models.MembreEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateEmbauche")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Poste")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Membres");
                });

            modelBuilder.Entity("Gestion_Projet.Models.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ChefProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFinPrevue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChefProjetId");

                    b.ToTable("Projets", t =>
                        {
                            t.HasCheckConstraint("CK_Projet_Budget", "\"Budget\" IS NULL OR \"Budget\" >= 0");

                            t.HasCheckConstraint("CK_Projet_DateFinPrevue", "\"DateFinPrevue\" IS NULL OR \"DateFinPrevue\" >= \"DateDebut\"");
                        });
                });

            modelBuilder.Entity("Gestion_Projet.Models.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstTerminee")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MembreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembreId");

                    b.HasIndex("ProjetId");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("Gestion_Projet.Models.Projet", b =>
                {
                    b.HasOne("Gestion_Projet.Models.MembreEquipe", "ChefProjet")
                        .WithMany("ProjetsLed")
                        .HasForeignKey("ChefProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChefProjet");
                });

            modelBuilder.Entity("Gestion_Projet.Models.Tache", b =>
                {
                    b.HasOne("Gestion_Projet.Models.MembreEquipe", "Membre")
                        .WithMany("Taches")
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Projet.Models.Projet", "Projet")
                        .WithMany("Taches")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Gestion_Projet.Models.MembreEquipe", b =>
                {
                    b.Navigation("ProjetsLed");

                    b.Navigation("Taches");
                });

            modelBuilder.Entity("Gestion_Projet.Models.Projet", b =>
                {
                    b.Navigation("Taches");
                });
#pragma warning restore 612, 618
        }
    }
}
